# Copyright (C) 2021 - 2025, Shanghai Yunsilicon Technology Co., Ltd.

# coding: utf-8

"""
    Ceph REST API

    This is the official Ceph REST API

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import re  # noqa: F401
import io
import warnings

from pydantic import validate_arguments, ValidationError

from pydantic import StrictStr

from typing import Any, Dict, Optional

from brain.clients.ceph.models.api_block_image_image_spec_snap_post_request import ApiBlockImageImageSpecSnapPostRequest
from brain.clients.ceph.models.api_block_image_image_spec_snap_snapshot_name_clone_post_request import ApiBlockImageImageSpecSnapSnapshotNameClonePostRequest
from brain.clients.ceph.models.api_block_image_image_spec_snap_snapshot_name_put_request import ApiBlockImageImageSpecSnapSnapshotNamePutRequest

from brain.clients.ceph.api_client import ApiClient
from brain.clients.ceph.api_response import ApiResponse
from brain.clients.ceph.exceptions import (  # noqa: F401
    ApiTypeError,
    ApiValueError
)


class RbdSnapshotApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client

    @validate_arguments
    def api_block_image_image_spec_snap_post(self, image_spec : StrictStr, api_block_image_image_spec_snap_post_request : Optional[ApiBlockImageImageSpecSnapPostRequest] = None, **kwargs) -> object:  # noqa: E501
        """api_block_image_image_spec_snap_post  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.api_block_image_image_spec_snap_post(image_spec, api_block_image_image_spec_snap_post_request, async_req=True)
        >>> result = thread.get()

        :param image_spec: (required)
        :type image_spec: str
        :param api_block_image_image_spec_snap_post_request:
        :type api_block_image_image_spec_snap_post_request: ApiBlockImageImageSpecSnapPostRequest
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: object
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the api_block_image_image_spec_snap_post_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.api_block_image_image_spec_snap_post_with_http_info(image_spec, api_block_image_image_spec_snap_post_request, **kwargs)  # noqa: E501

    @validate_arguments
    def api_block_image_image_spec_snap_post_with_http_info(self, image_spec : StrictStr, api_block_image_image_spec_snap_post_request : Optional[ApiBlockImageImageSpecSnapPostRequest] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """api_block_image_image_spec_snap_post  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.api_block_image_image_spec_snap_post_with_http_info(image_spec, api_block_image_image_spec_snap_post_request, async_req=True)
        >>> result = thread.get()

        :param image_spec: (required)
        :type image_spec: str
        :param api_block_image_image_spec_snap_post_request:
        :type api_block_image_image_spec_snap_post_request: ApiBlockImageImageSpecSnapPostRequest
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(object, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'image_spec',
            'api_block_image_image_spec_snap_post_request'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method api_block_image_image_spec_snap_post" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['image_spec']:
            _path_params['image_spec'] = _params['image_spec']


        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        if _params['api_block_image_image_spec_snap_post_request'] is not None:
            _body_params = _params['api_block_image_image_spec_snap_post_request']

        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/vnd.ceph.api.v1.0+json'])  # noqa: E501

        # set the HTTP header `Content-Type`
        _content_types_list = _params.get('_content_type',
            self.api_client.select_header_content_type(
                ['application/json']))
        if _content_types_list:
                _header_params['Content-Type'] = _content_types_list

        # authentication setting
        _auth_settings = ['BearerAuth']  # noqa: E501

        _response_types_map = {
            '201': "object",
            '202': "object",
            '400': None,
            '401': None,
            '403': None,
            '500': None,
        }

        return self.api_client.call_api(
            '/api/block/image/{image_spec}/snap', 'POST',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @validate_arguments
    def api_block_image_image_spec_snap_snapshot_name_clone_post(self, image_spec : StrictStr, snapshot_name : StrictStr, api_block_image_image_spec_snap_snapshot_name_clone_post_request : Optional[ApiBlockImageImageSpecSnapSnapshotNameClonePostRequest] = None, **kwargs) -> object:  # noqa: E501
        """api_block_image_image_spec_snap_snapshot_name_clone_post  # noqa: E501

                 Clones a snapshot to an image           # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.api_block_image_image_spec_snap_snapshot_name_clone_post(image_spec, snapshot_name, api_block_image_image_spec_snap_snapshot_name_clone_post_request, async_req=True)
        >>> result = thread.get()

        :param image_spec: (required)
        :type image_spec: str
        :param snapshot_name: (required)
        :type snapshot_name: str
        :param api_block_image_image_spec_snap_snapshot_name_clone_post_request:
        :type api_block_image_image_spec_snap_snapshot_name_clone_post_request: ApiBlockImageImageSpecSnapSnapshotNameClonePostRequest
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: object
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the api_block_image_image_spec_snap_snapshot_name_clone_post_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.api_block_image_image_spec_snap_snapshot_name_clone_post_with_http_info(image_spec, snapshot_name, api_block_image_image_spec_snap_snapshot_name_clone_post_request, **kwargs)  # noqa: E501

    @validate_arguments
    def api_block_image_image_spec_snap_snapshot_name_clone_post_with_http_info(self, image_spec : StrictStr, snapshot_name : StrictStr, api_block_image_image_spec_snap_snapshot_name_clone_post_request : Optional[ApiBlockImageImageSpecSnapSnapshotNameClonePostRequest] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """api_block_image_image_spec_snap_snapshot_name_clone_post  # noqa: E501

                 Clones a snapshot to an image           # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.api_block_image_image_spec_snap_snapshot_name_clone_post_with_http_info(image_spec, snapshot_name, api_block_image_image_spec_snap_snapshot_name_clone_post_request, async_req=True)
        >>> result = thread.get()

        :param image_spec: (required)
        :type image_spec: str
        :param snapshot_name: (required)
        :type snapshot_name: str
        :param api_block_image_image_spec_snap_snapshot_name_clone_post_request:
        :type api_block_image_image_spec_snap_snapshot_name_clone_post_request: ApiBlockImageImageSpecSnapSnapshotNameClonePostRequest
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(object, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'image_spec',
            'snapshot_name',
            'api_block_image_image_spec_snap_snapshot_name_clone_post_request'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method api_block_image_image_spec_snap_snapshot_name_clone_post" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['image_spec']:
            _path_params['image_spec'] = _params['image_spec']

        if _params['snapshot_name']:
            _path_params['snapshot_name'] = _params['snapshot_name']


        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        if _params['api_block_image_image_spec_snap_snapshot_name_clone_post_request'] is not None:
            _body_params = _params['api_block_image_image_spec_snap_snapshot_name_clone_post_request']

        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/vnd.ceph.api.v1.0+json'])  # noqa: E501

        # set the HTTP header `Content-Type`
        _content_types_list = _params.get('_content_type',
            self.api_client.select_header_content_type(
                ['application/json']))
        if _content_types_list:
                _header_params['Content-Type'] = _content_types_list

        # authentication setting
        _auth_settings = ['BearerAuth']  # noqa: E501

        _response_types_map = {
            '201': "object",
            '202': "object",
            '400': None,
            '401': None,
            '403': None,
            '500': None,
        }

        return self.api_client.call_api(
            '/api/block/image/{image_spec}/snap/{snapshot_name}/clone', 'POST',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @validate_arguments
    def api_block_image_image_spec_snap_snapshot_name_delete(self, image_spec : StrictStr, snapshot_name : StrictStr, **kwargs) -> object:  # noqa: E501
        """api_block_image_image_spec_snap_snapshot_name_delete  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.api_block_image_image_spec_snap_snapshot_name_delete(image_spec, snapshot_name, async_req=True)
        >>> result = thread.get()

        :param image_spec: (required)
        :type image_spec: str
        :param snapshot_name: (required)
        :type snapshot_name: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: object
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the api_block_image_image_spec_snap_snapshot_name_delete_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.api_block_image_image_spec_snap_snapshot_name_delete_with_http_info(image_spec, snapshot_name, **kwargs)  # noqa: E501

    @validate_arguments
    def api_block_image_image_spec_snap_snapshot_name_delete_with_http_info(self, image_spec : StrictStr, snapshot_name : StrictStr, **kwargs) -> ApiResponse:  # noqa: E501
        """api_block_image_image_spec_snap_snapshot_name_delete  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.api_block_image_image_spec_snap_snapshot_name_delete_with_http_info(image_spec, snapshot_name, async_req=True)
        >>> result = thread.get()

        :param image_spec: (required)
        :type image_spec: str
        :param snapshot_name: (required)
        :type snapshot_name: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(object, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'image_spec',
            'snapshot_name'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method api_block_image_image_spec_snap_snapshot_name_delete" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['image_spec']:
            _path_params['image_spec'] = _params['image_spec']

        if _params['snapshot_name']:
            _path_params['snapshot_name'] = _params['snapshot_name']


        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/vnd.ceph.api.v1.0+json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['BearerAuth']  # noqa: E501

        _response_types_map = {
            '202': "object",
            '204': "object",
            '400': None,
            '401': None,
            '403': None,
            '500': None,
        }

        return self.api_client.call_api(
            '/api/block/image/{image_spec}/snap/{snapshot_name}', 'DELETE',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @validate_arguments
    def api_block_image_image_spec_snap_snapshot_name_put(self, image_spec : StrictStr, snapshot_name : StrictStr, api_block_image_image_spec_snap_snapshot_name_put_request : Optional[ApiBlockImageImageSpecSnapSnapshotNamePutRequest] = None, **kwargs) -> object:  # noqa: E501
        """api_block_image_image_spec_snap_snapshot_name_put  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.api_block_image_image_spec_snap_snapshot_name_put(image_spec, snapshot_name, api_block_image_image_spec_snap_snapshot_name_put_request, async_req=True)
        >>> result = thread.get()

        :param image_spec: (required)
        :type image_spec: str
        :param snapshot_name: (required)
        :type snapshot_name: str
        :param api_block_image_image_spec_snap_snapshot_name_put_request:
        :type api_block_image_image_spec_snap_snapshot_name_put_request: ApiBlockImageImageSpecSnapSnapshotNamePutRequest
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: object
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the api_block_image_image_spec_snap_snapshot_name_put_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.api_block_image_image_spec_snap_snapshot_name_put_with_http_info(image_spec, snapshot_name, api_block_image_image_spec_snap_snapshot_name_put_request, **kwargs)  # noqa: E501

    @validate_arguments
    def api_block_image_image_spec_snap_snapshot_name_put_with_http_info(self, image_spec : StrictStr, snapshot_name : StrictStr, api_block_image_image_spec_snap_snapshot_name_put_request : Optional[ApiBlockImageImageSpecSnapSnapshotNamePutRequest] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """api_block_image_image_spec_snap_snapshot_name_put  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.api_block_image_image_spec_snap_snapshot_name_put_with_http_info(image_spec, snapshot_name, api_block_image_image_spec_snap_snapshot_name_put_request, async_req=True)
        >>> result = thread.get()

        :param image_spec: (required)
        :type image_spec: str
        :param snapshot_name: (required)
        :type snapshot_name: str
        :param api_block_image_image_spec_snap_snapshot_name_put_request:
        :type api_block_image_image_spec_snap_snapshot_name_put_request: ApiBlockImageImageSpecSnapSnapshotNamePutRequest
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(object, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'image_spec',
            'snapshot_name',
            'api_block_image_image_spec_snap_snapshot_name_put_request'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method api_block_image_image_spec_snap_snapshot_name_put" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['image_spec']:
            _path_params['image_spec'] = _params['image_spec']

        if _params['snapshot_name']:
            _path_params['snapshot_name'] = _params['snapshot_name']


        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        if _params['api_block_image_image_spec_snap_snapshot_name_put_request'] is not None:
            _body_params = _params['api_block_image_image_spec_snap_snapshot_name_put_request']

        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/vnd.ceph.api.v1.0+json'])  # noqa: E501

        # set the HTTP header `Content-Type`
        _content_types_list = _params.get('_content_type',
            self.api_client.select_header_content_type(
                ['application/json']))
        if _content_types_list:
                _header_params['Content-Type'] = _content_types_list

        # authentication setting
        _auth_settings = ['BearerAuth']  # noqa: E501

        _response_types_map = {
            '200': "object",
            '202': "object",
            '400': None,
            '401': None,
            '403': None,
            '500': None,
        }

        return self.api_client.call_api(
            '/api/block/image/{image_spec}/snap/{snapshot_name}', 'PUT',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))
