# Copyright (C) 2021 - 2025, Shanghai Yunsilicon Technology Co., Ltd.

# coding: utf-8

"""
    Dpu Agent API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, StrictInt
from brain.clients.dpuagent.models.network_config import NetworkConfig
from brain.clients.dpuagent.models.user_data import UserData

class CloudInitRequest(BaseModel):
    """
    CloudInitRequest
    """
    user_data: Optional[UserData] = None
    network_config: Optional[NetworkConfig] = None
    uuid: Optional[StrictInt] = None
    __properties = ["user_data", "network_config", "uuid"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> CloudInitRequest:
        """Create an instance of CloudInitRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of user_data
        if self.user_data:
            _dict['user_data'] = self.user_data.to_dict()
        # override the default output from pydantic by calling `to_dict()` of network_config
        if self.network_config:
            _dict['network_config'] = self.network_config.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> CloudInitRequest:
        """Create an instance of CloudInitRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return CloudInitRequest.parse_obj(obj)

        _obj = CloudInitRequest.parse_obj({
            "user_data": UserData.from_dict(obj.get("user_data")) if obj.get("user_data") is not None else None,
            "network_config": NetworkConfig.from_dict(obj.get("network_config")) if obj.get("network_config") is not None else None,
            "uuid": obj.get("uuid")
        })
        return _obj


