# Copyright (C) 2021 - 2025, Shanghai Yunsilicon Technology Co., Ltd.

# coding: utf-8

"""
    Dpu Agent API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictBool, StrictInt, StrictStr, conint, conlist

class DpuagentApiV1SchemasVblkSchemasCreateRequest(BaseModel):
    """
    DpuagentApiV1SchemasVblkSchemasCreateRequest
    """
    uuid: Optional[conint(strict=True, le=63, ge=1)] = None
    rbd_path: StrictStr = Field(...)
    vq_count: StrictInt = Field(...)
    vq_size: StrictInt = Field(...)
    gw_user: StrictStr = Field(...)
    gw_pwd: StrictStr = Field(...)
    gws: conlist(StrictStr) = Field(...)
    bootable: StrictBool = Field(...)
    __properties = ["uuid", "rbd_path", "vq_count", "vq_size", "gw_user", "gw_pwd", "gws", "bootable"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> DpuagentApiV1SchemasVblkSchemasCreateRequest:
        """Create an instance of DpuagentApiV1SchemasVblkSchemasCreateRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> DpuagentApiV1SchemasVblkSchemasCreateRequest:
        """Create an instance of DpuagentApiV1SchemasVblkSchemasCreateRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return DpuagentApiV1SchemasVblkSchemasCreateRequest.parse_obj(obj)

        _obj = DpuagentApiV1SchemasVblkSchemasCreateRequest.parse_obj({
            "uuid": obj.get("uuid"),
            "rbd_path": obj.get("rbd_path"),
            "vq_count": obj.get("vq_count"),
            "vq_size": obj.get("vq_size"),
            "gw_user": obj.get("gw_user"),
            "gw_pwd": obj.get("gw_pwd"),
            "gws": obj.get("gws"),
            "bootable": obj.get("bootable")
        })
        return _obj


