# Copyright (C) 2021 - 2025, Shanghai Yunsilicon Technology Co., Ltd.

# coding: utf-8

"""
    Dpu Agent API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class Mode(str, Enum):
    """
    An enumeration.
    """

    """
    allowed enum values
    """
    AUTO = 'auto'
    MANUAL = 'manual'

    @classmethod
    def from_json(cls, json_str: str) -> Mode:
        """Create an instance of Mode from a JSON string"""
        return Mode(json.loads(json_str))


