# Copyright (C) 2021 - 2025, Shanghai Yunsilicon Technology Co., Ltd.

# coding: utf-8

"""
    Dpu Agent API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictInt, conlist
from brain.clients.dpuagent.models.ethernet import Ethernet

class NetworkConfig(BaseModel):
    """
    NetworkConfig
    """
    ethernets: Optional[conlist(Ethernet)] = None
    version: Optional[StrictInt] = Field(2, description="Version 2 requires the system to support netplan")
    __properties = ["ethernets", "version"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> NetworkConfig:
        """Create an instance of NetworkConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in ethernets (list)
        _items = []
        if self.ethernets:
            for _item in self.ethernets:
                if _item:
                    _items.append(_item.to_dict())
            _dict['ethernets'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> NetworkConfig:
        """Create an instance of NetworkConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return NetworkConfig.parse_obj(obj)

        _obj = NetworkConfig.parse_obj({
            "ethernets": [Ethernet.from_dict(_item) for _item in obj.get("ethernets")] if obj.get("ethernets") is not None else None,
            "version": obj.get("version") if obj.get("version") is not None else 2
        })
        return _obj


