# Copyright (C) 2021 - 2025, Shanghai Yunsilicon Technology Co., Ltd.

# coding: utf-8

"""
    Dpu Agent API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, conint

class PolicingRequest(BaseModel):
    """
    PolicingRequest
    """
    bps_rate: conint(strict=True, ge=1) = Field(...)
    bps_burst: Optional[conint(strict=True, ge=1)] = None
    pps_rate: conint(strict=True, ge=1) = Field(...)
    pps_burst: Optional[conint(strict=True, ge=1)] = None
    __properties = ["bps_rate", "bps_burst", "pps_rate", "pps_burst"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> PolicingRequest:
        """Create an instance of PolicingRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> PolicingRequest:
        """Create an instance of PolicingRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return PolicingRequest.parse_obj(obj)

        _obj = PolicingRequest.parse_obj({
            "bps_rate": obj.get("bps_rate"),
            "bps_burst": obj.get("bps_burst"),
            "pps_rate": obj.get("pps_rate"),
            "pps_burst": obj.get("pps_burst")
        })
        return _obj


