# Copyright (C) 2021 - 2025, Shanghai Yunsilicon Technology Co., Ltd.

# coding: utf-8

"""
    Dpu Agent API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, conint

class QosRatioRequest(BaseModel):
    """
    QosRatioRequest
    """
    storage: conint(strict=True, ge=0) = Field(...)
    network: conint(strict=True, ge=0) = Field(...)
    __properties = ["storage", "network"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> QosRatioRequest:
        """Create an instance of QosRatioRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> QosRatioRequest:
        """Create an instance of QosRatioRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return QosRatioRequest.parse_obj(obj)

        _obj = QosRatioRequest.parse_obj({
            "storage": obj.get("storage"),
            "network": obj.get("network")
        })
        return _obj


