# Copyright (C) 2021 - 2025, Shanghai Yunsilicon Technology Co., Ltd.

# coding: utf-8

"""
    Dpu Agent API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictInt, conint

class QosSetRequest(BaseModel):
    """
    QosSetRequest
    """
    uuid: conint(strict=True, le=63, ge=1) = Field(...)
    rw_ios_per_sec: Optional[StrictInt] = None
    rw_mbytes_per_sec: Optional[StrictInt] = None
    r_mbytes_per_sec: Optional[StrictInt] = None
    w_mbytes_per_sec: Optional[StrictInt] = None
    __properties = ["uuid", "rw_ios_per_sec", "rw_mbytes_per_sec", "r_mbytes_per_sec", "w_mbytes_per_sec"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> QosSetRequest:
        """Create an instance of QosSetRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> QosSetRequest:
        """Create an instance of QosSetRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return QosSetRequest.parse_obj(obj)

        _obj = QosSetRequest.parse_obj({
            "uuid": obj.get("uuid"),
            "rw_ios_per_sec": obj.get("rw_ios_per_sec"),
            "rw_mbytes_per_sec": obj.get("rw_mbytes_per_sec"),
            "r_mbytes_per_sec": obj.get("r_mbytes_per_sec"),
            "w_mbytes_per_sec": obj.get("w_mbytes_per_sec")
        })
        return _obj


