# Copyright (C) 2021 - 2025, Shanghai Yunsilicon Technology Co., Ltd.

# coding: utf-8

"""
    Dpu Agent API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List
from pydantic import BaseModel, Field, StrictInt, StrictStr, conlist

class UuidUsageResponse(BaseModel):
    """
    Response model for Vsdk UUID usage  # noqa: E501
    """
    code: StrictInt = Field(..., description="return code of the API execution result")
    message: StrictStr = Field(..., description="Detailed execution results")
    blk_used: conlist(StrictInt) = Field(..., description="List of blk used UUIDs")
    xsc_used: conlist(StrictInt) = Field(..., description="List of xsc_net used UUIDs")
    unused: conlist(StrictInt) = Field(..., description="List of unused UUIDs")
    __properties = ["code", "message", "blk_used", "xsc_used", "unused"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> UuidUsageResponse:
        """Create an instance of UuidUsageResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> UuidUsageResponse:
        """Create an instance of UuidUsageResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return UuidUsageResponse.parse_obj(obj)

        _obj = UuidUsageResponse.parse_obj({
            "code": obj.get("code"),
            "message": obj.get("message"),
            "blk_used": obj.get("blk_used"),
            "xsc_used": obj.get("xsc_used"),
            "unused": obj.get("unused")
        })
        return _obj


