# Copyright (C) 2021 - 2025, Shanghai Yunsilicon Technology Co., Ltd.

# coding: utf-8

"""
    Dpu Agent API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr, conlist
from brain.clients.dpuagent.models.controller_info import ControllerInfo

class VBlkListResponse(BaseModel):
    """
    VBlkListResponse
    """
    code: StrictInt = Field(..., description="return code of the API execution result")
    message: StrictStr = Field(..., description="Detailed execution results")
    vblks: Optional[conlist(ControllerInfo)] = Field(None, description="List of virtual block controllers information")
    __properties = ["code", "message", "vblks"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> VBlkListResponse:
        """Create an instance of VBlkListResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in vblks (list)
        _items = []
        if self.vblks:
            for _item in self.vblks:
                if _item:
                    _items.append(_item.to_dict())
            _dict['vblks'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> VBlkListResponse:
        """Create an instance of VBlkListResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return VBlkListResponse.parse_obj(obj)

        _obj = VBlkListResponse.parse_obj({
            "code": obj.get("code"),
            "message": obj.get("message"),
            "vblks": [ControllerInfo.from_dict(_item) for _item in obj.get("vblks")] if obj.get("vblks") is not None else None
        })
        return _obj


