# Copyright (C) 2021 - 2025, Shanghai Yunsilicon Technology Co., Ltd.

# coding: utf-8

"""
    Ceph REST API

    This is the official Ceph REST API

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, StrictInt, StrictStr

class ApiBlockImageImageSpecPutRequest(BaseModel):
    """
    ApiBlockImageImageSpecPutRequest
    """
    configuration: Optional[StrictStr] = None
    features: Optional[StrictStr] = None
    name: Optional[StrictStr] = None
    size: Optional[StrictInt] = None
    __properties = ["configuration", "features", "name", "size"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ApiBlockImageImageSpecPutRequest:
        """Create an instance of ApiBlockImageImageSpecPutRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ApiBlockImageImageSpecPutRequest:
        """Create an instance of ApiBlockImageImageSpecPutRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ApiBlockImageImageSpecPutRequest.parse_obj(obj)

        _obj = ApiBlockImageImageSpecPutRequest.parse_obj({
            "configuration": obj.get("configuration"),
            "features": obj.get("features"),
            "name": obj.get("name"),
            "size": obj.get("size")
        })
        return _obj


