# Copyright (C) 2021 - 2025, Shanghai Yunsilicon Technology Co., Ltd.

# coding: utf-8

"""
    Ceph REST API

    This is the official Ceph REST API

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr

class ApiBlockImageImageSpecSnapSnapshotNameClonePostRequest(BaseModel):
    """
    ApiBlockImageImageSpecSnapSnapshotNameClonePostRequest
    """
    child_image_name: StrictStr = Field(...)
    child_namespace: Optional[StrictStr] = None
    child_pool_name: StrictStr = Field(...)
    configuration: Optional[StrictStr] = None
    data_pool: Optional[StrictStr] = None
    features: Optional[StrictStr] = None
    metadata: Optional[StrictStr] = None
    obj_size: Optional[StrictInt] = None
    stripe_count: Optional[StrictInt] = None
    stripe_unit: Optional[StrictStr] = None
    __properties = ["child_image_name", "child_namespace", "child_pool_name", "configuration", "data_pool", "features", "metadata", "obj_size", "stripe_count", "stripe_unit"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ApiBlockImageImageSpecSnapSnapshotNameClonePostRequest:
        """Create an instance of ApiBlockImageImageSpecSnapSnapshotNameClonePostRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ApiBlockImageImageSpecSnapSnapshotNameClonePostRequest:
        """Create an instance of ApiBlockImageImageSpecSnapSnapshotNameClonePostRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ApiBlockImageImageSpecSnapSnapshotNameClonePostRequest.parse_obj(obj)

        _obj = ApiBlockImageImageSpecSnapSnapshotNameClonePostRequest.parse_obj({
            "child_image_name": obj.get("child_image_name"),
            "child_namespace": obj.get("child_namespace"),
            "child_pool_name": obj.get("child_pool_name"),
            "configuration": obj.get("configuration"),
            "data_pool": obj.get("data_pool"),
            "features": obj.get("features"),
            "metadata": obj.get("metadata"),
            "obj_size": obj.get("obj_size"),
            "stripe_count": obj.get("stripe_count"),
            "stripe_unit": obj.get("stripe_unit")
        })
        return _obj


