# Copyright (C) 2021 - 2025, Shanghai Yunsilicon Technology Co., Ltd.

# coding: utf-8

"""
    Ceph REST API

    This is the official Ceph REST API

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, StrictBool, StrictInt, StrictStr, conlist

class ImageSnapshot(BaseModel):
    """
    ImageSnapshot
    """
    id: Optional[StrictInt] = None
    size: Optional[StrictInt] = None
    name: Optional[StrictStr] = None
    namespace: Optional[StrictInt] = None
    mirror_mode: Optional[StrictStr] = None
    timestamp: Optional[datetime] = None
    is_protected: Optional[StrictBool] = None
    children: Optional[conlist(Dict[str, Any])] = None
    disk_usage: Optional[StrictInt] = None
    __properties = ["id", "size", "name", "namespace", "mirror_mode", "timestamp", "is_protected", "children", "disk_usage"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ImageSnapshot:
        """Create an instance of ImageSnapshot from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ImageSnapshot:
        """Create an instance of ImageSnapshot from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ImageSnapshot.parse_obj(obj)

        _obj = ImageSnapshot.parse_obj({
            "id": obj.get("id"),
            "size": obj.get("size"),
            "name": obj.get("name"),
            "namespace": obj.get("namespace"),
            "mirror_mode": obj.get("mirror_mode"),
            "timestamp": obj.get("timestamp"),
            "is_protected": obj.get("is_protected"),
            "children": obj.get("children"),
            "disk_usage": obj.get("disk_usage")
        })
        return _obj


