# Copyright (C) 2021 - 2025, Shanghai Yunsilicon Technology Co., Ltd.

# coding: utf-8

"""
    Dpu Agent API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import re  # noqa: F401
import io
import warnings

from pydantic import validate_arguments, ValidationError

from pydantic import conint

from typing import Optional

from brain.clients.dpuagent.models.base_response_body import BaseResponseBody
from brain.clients.dpuagent.models.bdev_qos_info_response import BdevQosInfoResponse
from brain.clients.dpuagent.models.dpuagent_api_v1_schemas_vblk_schemas_create_request import DpuagentApiV1SchemasVblkSchemasCreateRequest
from brain.clients.dpuagent.models.dpuagent_api_v1_schemas_vblk_schemas_create_response_body import DpuagentApiV1SchemasVblkSchemasCreateResponseBody
from brain.clients.dpuagent.models.dpuagent_api_v1_schemas_vblk_schemas_delete_request import DpuagentApiV1SchemasVblkSchemasDeleteRequest
from brain.clients.dpuagent.models.qos_set_request import QosSetRequest
from brain.clients.dpuagent.models.v_blk_list_response import VBlkListResponse

from brain.clients.dpuagent.api_client import ApiClient
from brain.clients.dpuagent.api_response import ApiResponse
from brain.clients.dpuagent.exceptions import (  # noqa: F401
    ApiTypeError,
    ApiValueError
)


class VblkApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client

    @validate_arguments
    def create_vblk_dpu_agent_v1_vblk_add_post(self, dpuagent_api_v1_schemas_vblk_schemas_create_request : DpuagentApiV1SchemasVblkSchemasCreateRequest, **kwargs) -> DpuagentApiV1SchemasVblkSchemasCreateResponseBody:  # noqa: E501
        """Create Vblk  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.create_vblk_dpu_agent_v1_vblk_add_post(dpuagent_api_v1_schemas_vblk_schemas_create_request, async_req=True)
        >>> result = thread.get()

        :param dpuagent_api_v1_schemas_vblk_schemas_create_request: (required)
        :type dpuagent_api_v1_schemas_vblk_schemas_create_request: DpuagentApiV1SchemasVblkSchemasCreateRequest
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: DpuagentApiV1SchemasVblkSchemasCreateResponseBody
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the create_vblk_dpu_agent_v1_vblk_add_post_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.create_vblk_dpu_agent_v1_vblk_add_post_with_http_info(dpuagent_api_v1_schemas_vblk_schemas_create_request, **kwargs)  # noqa: E501

    @validate_arguments
    def create_vblk_dpu_agent_v1_vblk_add_post_with_http_info(self, dpuagent_api_v1_schemas_vblk_schemas_create_request : DpuagentApiV1SchemasVblkSchemasCreateRequest, **kwargs) -> ApiResponse:  # noqa: E501
        """Create Vblk  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.create_vblk_dpu_agent_v1_vblk_add_post_with_http_info(dpuagent_api_v1_schemas_vblk_schemas_create_request, async_req=True)
        >>> result = thread.get()

        :param dpuagent_api_v1_schemas_vblk_schemas_create_request: (required)
        :type dpuagent_api_v1_schemas_vblk_schemas_create_request: DpuagentApiV1SchemasVblkSchemasCreateRequest
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(DpuagentApiV1SchemasVblkSchemasCreateResponseBody, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'dpuagent_api_v1_schemas_vblk_schemas_create_request'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method create_vblk_dpu_agent_v1_vblk_add_post" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        if _params['dpuagent_api_v1_schemas_vblk_schemas_create_request'] is not None:
            _body_params = _params['dpuagent_api_v1_schemas_vblk_schemas_create_request']

        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # set the HTTP header `Content-Type`
        _content_types_list = _params.get('_content_type',
            self.api_client.select_header_content_type(
                ['application/json']))
        if _content_types_list:
                _header_params['Content-Type'] = _content_types_list

        # authentication setting
        _auth_settings = ['OAuth2PasswordBearer']  # noqa: E501

        _response_types_map = {
            '200': "DpuagentApiV1SchemasVblkSchemasCreateResponseBody",
            '422': "HTTPValidationError",
        }

        return self.api_client.call_api(
            '/dpu_agent/v1/vblk/add', 'POST',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @validate_arguments
    def delete_vblk_dpu_agent_v1_vblk_del_post(self, dpuagent_api_v1_schemas_vblk_schemas_delete_request : DpuagentApiV1SchemasVblkSchemasDeleteRequest, **kwargs) -> BaseResponseBody:  # noqa: E501
        """Delete Vblk  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.delete_vblk_dpu_agent_v1_vblk_del_post(dpuagent_api_v1_schemas_vblk_schemas_delete_request, async_req=True)
        >>> result = thread.get()

        :param dpuagent_api_v1_schemas_vblk_schemas_delete_request: (required)
        :type dpuagent_api_v1_schemas_vblk_schemas_delete_request: DpuagentApiV1SchemasVblkSchemasDeleteRequest
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: BaseResponseBody
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the delete_vblk_dpu_agent_v1_vblk_del_post_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.delete_vblk_dpu_agent_v1_vblk_del_post_with_http_info(dpuagent_api_v1_schemas_vblk_schemas_delete_request, **kwargs)  # noqa: E501

    @validate_arguments
    def delete_vblk_dpu_agent_v1_vblk_del_post_with_http_info(self, dpuagent_api_v1_schemas_vblk_schemas_delete_request : DpuagentApiV1SchemasVblkSchemasDeleteRequest, **kwargs) -> ApiResponse:  # noqa: E501
        """Delete Vblk  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.delete_vblk_dpu_agent_v1_vblk_del_post_with_http_info(dpuagent_api_v1_schemas_vblk_schemas_delete_request, async_req=True)
        >>> result = thread.get()

        :param dpuagent_api_v1_schemas_vblk_schemas_delete_request: (required)
        :type dpuagent_api_v1_schemas_vblk_schemas_delete_request: DpuagentApiV1SchemasVblkSchemasDeleteRequest
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(BaseResponseBody, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'dpuagent_api_v1_schemas_vblk_schemas_delete_request'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_vblk_dpu_agent_v1_vblk_del_post" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        if _params['dpuagent_api_v1_schemas_vblk_schemas_delete_request'] is not None:
            _body_params = _params['dpuagent_api_v1_schemas_vblk_schemas_delete_request']

        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # set the HTTP header `Content-Type`
        _content_types_list = _params.get('_content_type',
            self.api_client.select_header_content_type(
                ['application/json']))
        if _content_types_list:
                _header_params['Content-Type'] = _content_types_list

        # authentication setting
        _auth_settings = ['OAuth2PasswordBearer']  # noqa: E501

        _response_types_map = {
            '200': "BaseResponseBody",
            '422': "HTTPValidationError",
        }

        return self.api_client.call_api(
            '/dpu_agent/v1/vblk/del', 'POST',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @validate_arguments
    def get_bdev_qos_limit_dpu_agent_v1_bdev_qos_get_get(self, uuid : conint(strict=True, le=63, ge=0), **kwargs) -> BdevQosInfoResponse:  # noqa: E501
        """Get Bdev Qos Limit  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_bdev_qos_limit_dpu_agent_v1_bdev_qos_get_get(uuid, async_req=True)
        >>> result = thread.get()

        :param uuid: (required)
        :type uuid: int
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: BdevQosInfoResponse
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the get_bdev_qos_limit_dpu_agent_v1_bdev_qos_get_get_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.get_bdev_qos_limit_dpu_agent_v1_bdev_qos_get_get_with_http_info(uuid, **kwargs)  # noqa: E501

    @validate_arguments
    def get_bdev_qos_limit_dpu_agent_v1_bdev_qos_get_get_with_http_info(self, uuid : conint(strict=True, le=63, ge=0), **kwargs) -> ApiResponse:  # noqa: E501
        """Get Bdev Qos Limit  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_bdev_qos_limit_dpu_agent_v1_bdev_qos_get_get_with_http_info(uuid, async_req=True)
        >>> result = thread.get()

        :param uuid: (required)
        :type uuid: int
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(BdevQosInfoResponse, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'uuid'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_bdev_qos_limit_dpu_agent_v1_bdev_qos_get_get" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        if _params.get('uuid') is not None:  # noqa: E501
            _query_params.append(('uuid', _params['uuid']))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['OAuth2PasswordBearer']  # noqa: E501

        _response_types_map = {
            '200': "BdevQosInfoResponse",
            '422': "HTTPValidationError",
        }

        return self.api_client.call_api(
            '/dpu_agent/v1/bdev_qos/get', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @validate_arguments
    def list_vblk_controllers_dpu_agent_v1_vblk_list_get(self, uuid : Optional[conint(strict=True, le=63, ge=0)] = None, **kwargs) -> VBlkListResponse:  # noqa: E501
        """List Vblk Controllers  # noqa: E501

        List virtual block controllers  Args: - `uuid`: Optional controller uuid to filter the results. If provided, only returns                information about the specified controller.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.list_vblk_controllers_dpu_agent_v1_vblk_list_get(uuid, async_req=True)
        >>> result = thread.get()

        :param uuid:
        :type uuid: int
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: VBlkListResponse
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the list_vblk_controllers_dpu_agent_v1_vblk_list_get_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.list_vblk_controllers_dpu_agent_v1_vblk_list_get_with_http_info(uuid, **kwargs)  # noqa: E501

    @validate_arguments
    def list_vblk_controllers_dpu_agent_v1_vblk_list_get_with_http_info(self, uuid : Optional[conint(strict=True, le=63, ge=0)] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """List Vblk Controllers  # noqa: E501

        List virtual block controllers  Args: - `uuid`: Optional controller uuid to filter the results. If provided, only returns                information about the specified controller.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.list_vblk_controllers_dpu_agent_v1_vblk_list_get_with_http_info(uuid, async_req=True)
        >>> result = thread.get()

        :param uuid:
        :type uuid: int
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(VBlkListResponse, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'uuid'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method list_vblk_controllers_dpu_agent_v1_vblk_list_get" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        if _params.get('uuid') is not None:  # noqa: E501
            _query_params.append(('uuid', _params['uuid']))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['OAuth2PasswordBearer']  # noqa: E501

        _response_types_map = {
            '200': "VBlkListResponse",
            '422': "HTTPValidationError",
        }

        return self.api_client.call_api(
            '/dpu_agent/v1/vblk/list', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @validate_arguments
    def set_bdev_qos_limit_dpu_agent_v1_bdev_qos_set_post(self, qos_set_request : QosSetRequest, **kwargs) -> BaseResponseBody:  # noqa: E501
        """Set Bdev Qos Limit  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.set_bdev_qos_limit_dpu_agent_v1_bdev_qos_set_post(qos_set_request, async_req=True)
        >>> result = thread.get()

        :param qos_set_request: (required)
        :type qos_set_request: QosSetRequest
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: BaseResponseBody
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the set_bdev_qos_limit_dpu_agent_v1_bdev_qos_set_post_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.set_bdev_qos_limit_dpu_agent_v1_bdev_qos_set_post_with_http_info(qos_set_request, **kwargs)  # noqa: E501

    @validate_arguments
    def set_bdev_qos_limit_dpu_agent_v1_bdev_qos_set_post_with_http_info(self, qos_set_request : QosSetRequest, **kwargs) -> ApiResponse:  # noqa: E501
        """Set Bdev Qos Limit  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.set_bdev_qos_limit_dpu_agent_v1_bdev_qos_set_post_with_http_info(qos_set_request, async_req=True)
        >>> result = thread.get()

        :param qos_set_request: (required)
        :type qos_set_request: QosSetRequest
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(BaseResponseBody, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'qos_set_request'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method set_bdev_qos_limit_dpu_agent_v1_bdev_qos_set_post" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        if _params['qos_set_request'] is not None:
            _body_params = _params['qos_set_request']

        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # set the HTTP header `Content-Type`
        _content_types_list = _params.get('_content_type',
            self.api_client.select_header_content_type(
                ['application/json']))
        if _content_types_list:
                _header_params['Content-Type'] = _content_types_list

        # authentication setting
        _auth_settings = ['OAuth2PasswordBearer']  # noqa: E501

        _response_types_map = {
            '200': "BaseResponseBody",
            '422': "HTTPValidationError",
        }

        return self.api_client.call_api(
            '/dpu_agent/v1/bdev_qos/set', 'POST',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))
