[DEFAULT]
webhook_url = https://webhook.yunsilicon.com/open-apis/bot/v2/hook/xxxxx
yuntester_platform = https://yuntester.yunsilicon.com

[smtp]
host = smtp.feishu.cn
port = 465
user = yuntester@yunsilicon.com
password = VIgB7YFDX9Y3g7Dw
