openapi: 3.0.3
info:
  title: Brain API
  version: 0.1.0
paths:
  /login:
    post:
      tags:
        - auth
      summary: Login For Access Token
      operationId: login_for_access_token_login_post
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Body_login_for_access_token_login_post'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/devices:
    get:
      tags:
        - device
      summary: Get All Devices
      operationId: get_all_devices_api_devices_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ServerDetailResponse'
                title: Response Get All Devices Api Devices Get
      security:
        - OAuth2PasswordBearer: []
    post:
      tags:
        - device
      summary: Create Device
      operationId: create_device_api_devices_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ServerRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerDetailResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
        - OAuth2PasswordBearer: []
  /api/devices/{device_id}:
    get:
      tags:
        - device
      summary: Get Device
      operationId: get_device_api_devices__device_id__get
      parameters:
        - name: device_id
          in: path
          required: true
          schema:
            type: string
            title: Device Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerDetailResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
        - OAuth2PasswordBearer: []
    put:
      tags:
        - device
      summary: Update Device
      operationId: update_device_api_devices__device_id__put
      parameters:
        - name: device_id
          in: path
          required: true
          schema:
            type: string
            title: Device Id
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ServerUpdateRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerDetailResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
        - OAuth2PasswordBearer: []
    delete:
      tags:
        - device
      summary: Delete Device
      operationId: delete_device_api_devices__device_id__delete
      parameters:
        - name: device_id
          in: path
          required: true
          schema:
            type: string
            title: Device Id
      responses:
        '204':
          description: Successful Response
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
        - OAuth2PasswordBearer: []
  /api/tag:
    post:
      tags:
        - tags
      summary: Create Tags
      operationId: create_tags_api_tag_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TagsRequest'
        required: true
      responses:
        '201':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TagsRequest'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
        - OAuth2PasswordBearer: []
  /api/tags:
    get:
      tags:
        - tags
      summary: Get All Tags
      operationId: get_all_tags_api_tags_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TagsResponse'
      security:
        - OAuth2PasswordBearer: []
  /api/tag/{tag_id}:
    delete:
      tags:
        - tags
      summary: Delete Tag
      operationId: delete_tag_api_tag__tag_id__delete
      parameters:
        - name: tag_id
          in: path
          required: true
          schema:
            type: string
            title: Tag Id
      responses:
        '204':
          description: Successful Response
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
        - OAuth2PasswordBearer: []
components:
  schemas:
    AIDPU_Nic:
      type: object
      required:
        - type
        - mac
        - bdf
        - sn
        - soc_ip
      properties:
        type:
          type: string
          title: Type
        mac:
          type: array
          items:
            type: string
          title: Mac
        bdf:
          type: string
          title: Bdf
        sn:
          type: string
          title: Sn
        soc_ip:
          type: string
          format: ipv4
          title: Soc Ip
        aidpu_sn:
          type: string
          title: Aidpu Sn
        firmware_version:
          type: string
          title: Firmware Version
        management_ip:
          type: string
          title: Management Ip
      title: AIDPU_Nic
    BMC:
      type: object
      required:
        - hostname
      properties:
        ip:
          type: string
          format: ipv4
          title: Ip
        hostname:
          type: string
          title: Hostname
      title: BMC
    Body_login_for_access_token_login_post:
      type: object
      properties:
        grant_type:
          type: string
          title: Grant Type
          default: password
        username:
          type: string
          title: Username
        password:
          type: string
          title: Password
        scope:
          type: string
          title: Scope
          default: ''
        client_id:
          type: string
          title: Client Id
        client_secret:
          type: string
          title: Client Secret
        refresh_token:
          type: string
          title: Refresh Token
      title: Body_login_for_access_token_login_post
    DeviceRequest:
      type: object
      required:
        - ip
        - username
        - password
      properties:
        sn:
          type: string
          title: Sn
        ip:
          type: string
          format: ipv4
          title: Ip
        username:
          type: string
          title: Username
        password:
          type: string
          title: Password
      title: DeviceRequest
    DeviceResponse:
      type: object
      required:
        - ip
        - username
      properties:
        sn:
          type: string
          title: Sn
        ip:
          type: string
          format: ipv4
          title: Ip
        username:
          type: string
          title: Username
      title: DeviceResponse
    HTTPValidationError:
      type: object
      properties:
        detail:
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
      title: HTTPValidationError
    NicBase:
      type: object
      required:
        - type
        - mac
        - bdf
        - sn
      properties:
        type:
          type: string
          title: Type
        mac:
          type: array
          items:
            type: string
          title: Mac
        bdf:
          type: string
          title: Bdf
        sn:
          type: string
          title: Sn
      title: NicBase
    ServerDetailResponse:
      type: object
      required:
        - bmc
        - device
      properties:
        bmc:
          $ref: '#/components/schemas/BMC'
        device:
          $ref: '#/components/schemas/DeviceResponse'
        nics:
          type: array
          items:
            anyOf:
              - $ref: '#/components/schemas/NicBase'
              - $ref: '#/components/schemas/AIDPU_Nic'
          title: Nics
        os_types:
          type: array
          items:
            type: string
          title: Os Types
          default: []
        tags:
          type: array
          items:
            type: string
          title: Tags
          default: []
        notes:
          type: string
          title: Notes
        user:
          type: string
          title: User
        time:
          type: string
          title: Time
        created_at:
          type: string
          title: Created At
        updated_at:
          type: string
          title: Updated At
        id:
          type: string
          title: Id
      title: ServerDetailResponse
    ServerRequest:
      type: object
      required:
        - bmc
        - device
      properties:
        bmc:
          $ref: '#/components/schemas/BMC'
        device:
          $ref: '#/components/schemas/DeviceRequest'
        nics:
          type: array
          items:
            anyOf:
              - $ref: '#/components/schemas/NicBase'
              - $ref: '#/components/schemas/AIDPU_Nic'
          title: Nics
        os_types:
          type: array
          items:
            type: string
          title: Os Types
          default: []
        tags:
          type: array
          items:
            type: string
          title: Tags
          default: []
        notes:
          type: string
          title: Notes
      title: ServerRequest
    ServerUpdateRequest:
      type: object
      properties:
        auto:
          type: boolean
          title: Auto
          default: false
        device:
          $ref: '#/components/schemas/DeviceRequest'
        bmc:
          $ref: '#/components/schemas/BMC'
        nics:
          type: array
          items:
            anyOf:
              - $ref: '#/components/schemas/NicBase'
              - $ref: '#/components/schemas/AIDPU_Nic'
          title: Nics
        os_types:
          type: array
          items:
            type: string
          title: Os Types
          default: []
        tags:
          type: array
          items:
            type: string
          title: Tags
        notes:
          type: string
          title: Notes
        time:
          type: string
          title: Time
      title: ServerUpdateRequest
    TagResponse:
      type: object
      required:
        - name
        - color
        - id
      properties:
        name:
          type: string
          title: Name
        color:
          type: string
          title: Color
        id:
          type: string
          title: Id
      title: TagResponse
    TagsRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          title: Name
      title: TagsRequest
    TagsResponse:
      type: object
      required:
        - tags
      properties:
        tags:
          type: array
          items:
            $ref: '#/components/schemas/TagResponse'
          title: Tags
      title: TagsResponse
    TokenResponse:
      type: object
      required:
        - access_token
        - token_type
        - expires_in
        - refresh_token
      properties:
        access_token:
          type: string
          title: Access Token
        token_type:
          type: string
          title: Token Type
        expires_in:
          type: integer
          title: Expires In
        refresh_token:
          type: string
          title: Refresh Token
      title: TokenResponse
    ValidationError:
      type: object
      required:
        - loc
        - msg
        - type
      properties:
        loc:
          type: array
          items:
            anyOf:
              - type: string
              - type: integer
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      title: ValidationError
  securitySchemes:
    OAuth2PasswordBearer:
      type: oauth2
      flows:
        password:
          tokenUrl: login
          scopes: {}